Remove wind speed from analytical spectra, and generally tweak
wave-harmonic/crest pull request #820
Opened 2021-05-09 11:44 UTC by huwb

The wind speed should no longer be baked into the spectrum. The spectrum should give the character of the ocean for any wind speed, and the wind speed is applied based on current wind conditions dynamically.

I removed the wind speed from the analytical spectra which seemed to work.

While doing so i found the 'small wave multiplier' is only really needed for JONSWAP, and have an effect akin to simple scaling for the otehr spectra. Given we already have a multiplier param on the spectrum, its useless and another param that users have to grapple with. I got good results removing params from phillips/moskowitz by tweaking a good default value, and the parameter ranges for jonswap look good now too.

Most of the jonswap tweaking range is exponentially distributed at the low end, so i made the slider exponential. This has the unfortunate side effect of making the automatic value text box show the exponentiated value rather than the linear one. I decided to modify the label which gets us across the line. Dale i have not compared with the exponential slider work you did, let me know if something should change here.

2021-05-10 23:17 UTC, daleeidd requested changes
Nice. Might as well use the PowerSlider function from reflection. And if not too much trouble needs release notes entry.

2021-05-11 06:10 UTC, huwb commented
Sad that the power slider did not work out (comment above). I'll clean up the commented code if you agree this is the way forward.

2021-05-11 20:30 UTC, huwb commented
I used your code and it seems to work well

2021-05-12 06:35 UTC, huwb commented on crest/Assets/Crest/Crest/Scripts/Shapes/OceanWaveSpectrum.cs
> +                    spec._fetch = EditorGUILayout.FloatField(s_labelFetch, spec._fetch);
done now

2021-05-12 06:36 UTC, huwb commented
thanks for the feedback/help, mergin

2021-05-12 06:36 UTC, merged