Water body auto clip-include
wave-harmonic/crest pull request #912
Opened 2021-09-19 12:38 UTC by huwb

Make waterbody automatically clip-include

If clipping is enabled and clipping set to remove everything by default, then the waterbody ensures its area is clip-included.

This seems good to me, but needs the ocean lifetime stuff to ensure OnEnable is called after the OceanRenderer.

No urgency on this so ill just park it here.

2021-10-14 06:29 UTC, huwb commented
You mean you are setting to clip everything by default, then adding a box to include, then a sphere to cut out again?

2021-10-31 13:11 UTC, huwb commented on crest/Assets/Crest/Crest/Scripts/WaterBody.cs
> +
thanks fixed

2021-10-31 13:38 UTC, huwb commented on crest/Assets/Crest/Crest/Scripts/WaterBody.cs
> +        private void Update()
done now

2021-11-01 04:42 UTC, daleeidd commented on crest/Assets/Crest/Crest/Scripts/WaterBody.cs
> +        private void Update()
Thanks

2021-11-01 04:42 UTC, daleeidd approved these changes
Nice work.

2021-11-01 04:59 UTC, daleeidd requested changes
I missed this but the execution order will need to be after the OR for it to work in builds. Can merge after that is done.

2021-11-13 08:11 UTC, daleeidd approved these changes
I did the last review items. Ready to merge when you're ready.

2021-12-11 13:17 UTC, daleeidd commented
@huwb happy to resolve release note conflict and merge if you're fine with everything.

2021-12-11 14:15 UTC, huwb commented
thanks for bumping

what is the requirement for the update order? i'm not super against it but just curious if we can avoid it. the update order adds implicit dependencies between parts of the code which are not documented and can break, so previously i did a push to minimise the use of update orders.

perhaps an alternative is to call our own update function on all waterbodies from the OceanRenderer component. however im aware this is editor code and maybe not worth it. but it might be good to record what the update order dependence is in a comment.

2021-12-12 10:15 UTC, daleeidd commented
> what is the requirement for the update order?

The Update method is stripped from builds. So this feature will only get triggered from OnEnable in builds which is execution order dependent on OR.

> but it might be good to record what the update order dependence is in a comment.

Done.

> perhaps an alternative is to call our own update function on all waterbodies from the OceanRenderer component.

Agreed. Going to look at doing that next. I am considering using C# delegates or would you prefer we maintain our own registry and call directly?

2021-12-12 19:35 UTC, huwb commented
Ohh it's OnEnable. I guess this is part of the same update issue we're discussing oh the other pr that ensures events get called at the right times when OR enabled/disabled. Do you know which PR I mean? I'll see if I can find it after posting this.

2021-12-12 20:14 UTC, huwb commented
Ok yeah #629 . ideally we could converge that rather than workaround it here. I'll try to reply there shortly.

I'd be fine with the changes as is in the meantime - using update order - but would be good to revert once #629 merges. or we could try to get #629 done first.

2021-12-15 13:47 UTC, merged